development:
  adapter: mysql
  encoding: utf8
  database: nan_development
  username: root
  pool: 5
  timeout: 5000

test: &test
  adapter: mysql
  encoding: utf8
  database: nan_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  database: nan_development
  pool: 5
  timeout: 5000
